
- hosts: database
  become: true
  gather_facts: no
  vars_files:
   - vars
  roles:
   - gitlab_db

- hosts: app
  become: true
  gather_facts: no
  vars_files:
   - vars 
  roles:
   - gitlab_app

