
- name: update repositories cache
  apt:
     update_cache: yes

- name: install dependencies
  apt:
     name: "{{ packages }}"
  vars:
     packages:
      - postgresql
      - postgresql-contrib
      - python-psycopg2

- name: make postgres listen for all hosts
  lineinfile:
    path: /etc/postgresql/10/main/postgresql.conf
    regexp: '^#listen_addresses'
    line: "listen_addresses = '*'"
    backrefs: yes

- name: add entry to pg_hba for all hosts
  lineinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    line: "host all all 0.0.0.0/0 trust"

- name: restart and enable postgres
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: create gitlab user 
  command: sudo -u postgres psql -c "create user gitlab with encrypted password '{{ gitlab_password }}';"
  ignore_errors: yes

- name: give gitlab superuser role
  command: sudo -u postgres psql -c "alter role gitlab superuser;"
  ignore_errors: yes

- name: create gitlab user database
  command: sudo -u postgres psql -c "create database gitlab;"
  ignore_errors: yes

- name: 
  command: sudo -u postgres psql -c "create database gitlab_production;"
  ignore_errors: yes



