
- name: update repositories cache
  apt:
     update_cache: yes
     cache_valid_time: 3600

- name: install dependencies
  apt:
     name: "{{ packages }}"
  vars:
     packages:
      - postgresql
      - postgresql-contrib
      - python-psycopg2

- name: make postgres listen for all hosts
  lineinfile:
    path: /etc/postgresql/10/main/postgresql.conf
    regexp: '^#listen_addresses'
    line: "listen_addresses = '*'"
    backrefs: yes
  register: postgresql_conf

- name: add entry to pg_hba for all hosts
  lineinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    line: "host all all 0.0.0.0/0 trust"
  register: pg_hba_conf

- name: restart and enable postgres
  service:
    name: postgresql
    state: restarted
    enabled: yes
  when: postgresql_conf is changed or pg_hba_conf is changed

- name: create gitlab user 
  command: sudo -u postgres psql -c "create user gitlab with encrypted password '{{ gitlab_password }}';"
  args:  
    warn: false
  register: command_result
  failed_when: "'ERROR:' in command_result.stderr"
  changed_when: "'already exists' not in command_result.stderr"

- name: give gitlab superuser role
  command: sudo -u postgres psql -c "alter role gitlab superuser;"
  args:
    warn: false
  failed_when: "'ERROR:' in command_result.stderr" 
  changed_when: "'already exists' not in command_result.stderr"

- name: create gitlab user database
  command: sudo -u postgres psql -c "create database gitlab;"
  args:  
    warn: false
  failed_when: "'ERROR:' in command_result.stderr"
  changed_when: "'already exists' not in command_result.stderr"

- name: create the gitlab_production database
  command: sudo -u postgres psql -c "create database gitlab_production;"
  args:
    warn: false
  failed_when: "'ERROR:' in command_result.stderr"
  changed_when: "'already exists' not in command_result.stderr"

