
- name: update repositories cache
  apt:
     update_cache: yes
     cache_valid_time: 3600

- name: install dependencies
  apt:
     name: "{{ packages }}"
  vars:
     packages:
      - curl
      - openssh-server
      - ca-certificates
      - postfix

- name: get the gitlab repository script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: 0700

- name: run the gitlab repository script
  command: /tmp/script.deb.sh

- name: install dependencies
  apt:
     name: "{{ packages }}"
  vars:
     packages:
      - gitlab-ee
     environment:
      EXTERNAL_URL: "{{ gitlab_url }}"

- name: add gitlab.rb
  template:
    src: source/gitlab.rb
    dest: /etc/gitlab/gitlab.rb

- name: reconfigure gitlab
  command: gitlab-ctl reconfigure

